stages:
  - build
  - deploy
  - deploy-ams

variables:
  PKG: api-mocker-server


# stage build - 安装 npm 依赖
install dependencies:
  stage: build
  tags:
    - f2e-runner
    - docker
  only:
    - develop
    - master
  except:
    changes:
      - "*.md"
  cache:
    key: "${CI_PROJECT_PATH}-${CI_COMMIT_REF_NAME}"
    paths:
      - node_modules/
    policy: pull-push # 拉取 npm 依赖缓存、更新 npm 依赖 & 推送 npm 依赖缓存
  script:
    - npm config set registry https://registry.npm.taobao.org/
    - npm config set production false
    - npm i
    - tar zcf ${PKG}-${CI_COMMIT_SHA:0:8}.tar.gz * .eslint* # 打代码包，做为 artifacts
    - md5sum ${PKG}-${CI_COMMIT_SHA:0:8}.tar.gz > ${PKG}-${CI_COMMIT_SHA:0:8}.tar.gz.md5
  artifacts:
    paths:
      - ${PKG}-${CI_COMMIT_SHA:0:8}.tar.gz
      - ${PKG}-${CI_COMMIT_SHA:0:8}.tar.gz.md5
    expire_in: 1 week

# stage deploy - 在测试环境（192.168.202.216 机器）上部署应用
deploy to development environment:
  stage: deploy
  tags:
    - f2e-runner
    - bash # 部署使用 shell executor，此 runner 就在目标机器 216 上
  only:
    - develop # 针对 develop 分支，部署测试环境
  except:
    changes:
      - "*.md"
  variables:
    GIT_STRATEGY: none
  dependencies:
    - install dependencies
  script:
    - tar xf ${PKG}-${CI_COMMIT_SHA:0:8}.tar.gz
    - ./bin/appctl.sh ${PKG} ${CI_COMMIT_SHA:0:8}

# stage deploy-ams - 在生产环境（生产机）上部署应用
deploy-ams to production environment:
  stage: deploy-ams
  tags:
    - f2e-prd
    - bash
  only:
    - master
  except:
    changes:
      - "*.md"
  variables:
    GIT_STRATEGY: none
  dependencies:
    - install dependencies
  script:
    - mv ${PKG}-${CI_COMMIT_SHA:0:8}.tar.gz* /var/cache/deploy/
    - sudo /opt/bin/deploy-f2e-api-mocker-server ${PKG} ${CI_COMMIT_SHA:0:8}
