version: "3"

services:
  mongo:
    build: ./mongo
    ports:
      - 7001:7001

  server:
    build: ./server
    network_mode: "service:mongo"
    depends_on:
      - mongo

  client:
    build: ./client
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8888:80"
    depends_on:
      - server
