version: "3"

services:
  mongo:
    build:
      context: '../'
      dockerfile: 'build-docker/mongo/Dockerfile'
    ports:
      - 7001:7001

  server:
    build:
      context: '../'
      dockerfile: 'build-docker/server/Dockerfile'
    network_mode: "service:mongo"
    depends_on:
      - mongo

  client:
    build:
      context: '../'
      dockerfile: build-docker/client/Dockerfile
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8888:80"
    depends_on:
      - server
